# Generated by Django 6.0.5 on 2026-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=50)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=50)),
                ('application_type', models.CharField(choices=[('recordation', 'Recordation'), ('renewal', 'Renewal'), ('change_of_ownership', 'Change of ownership'), ('change_of_name', 'Change of name'), ('discontinuation', 'Discontinuation')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('need_more_info', 'Need more Information'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
